function getData(){
    return data = [
        "./img/1.webp", "01",
        "./img/2.webp", "02",
        "./img/3.webp", "03",
        "./img/4.webp", "04",
        "./img/5.webp", "05",
        "./img/6.webp", "06",
        "./img/7.webp", "07",
        "./img/8.webp", "08",
        "./img/9.webp", "09",
        "./img/10.webp", "10",
        "./img/1.webp", "11",
        "./img/2.webp", "12",
        "./img/3.webp", "13",
        "./img/4.webp", "14",
        "./img/5.webp", "15",
        "./img/6.webp", "16",
        "./img/7.webp", "17",
        "./img/8.webp", "18",
        "./img/9.webp", "19",
        "./img/10.webp", "20",
        "./img/1.webp", "21",
        "./img/2.webp", "22",
        "./img/3.webp", "23",
        "./img/4.webp", "24",
        "./img/5.webp", "25",
        "./img/6.webp", "26",
        "./img/7.webp", "27",
        "./img/8.webp", "28",
        "./img/9.webp", "29",
    ];
}